// <auto-generated />
namespace Tienda.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class customuserfields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(customuserfields));
        
        string IMigrationMetadata.Id
        {
            get { return "201707230025217_custom-user-fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
