// <auto-generated />
namespace Tienda.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class producto_imageurl_notrequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(producto_imageurl_notrequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201707161617277_producto_imageurl_notrequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
